/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettotalpa;

import java.awt.GridLayout;

/**
 *
 * @author montedori.riccardo
 */
public class InterfacciaTalpa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaTalpa.class.getName());

    /**
     * Creates new form InterfacciaTalpa
     */
    private Buca[] buche = new Buca[4];
    private Talpa[] talpe = new Talpa[4];
    
    public InterfacciaTalpa() {
        initComponents();
        personalizzaInizializzazione();
    }
    
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acchiappa la Talpa - Progetto Java");
        setSize(500, 500);
        getContentPane().setLayout(new GridLayout(2, 2, 10, 10));
    }
    
    private void personalizzaInizializzazione() {
        for (int i = 0; i < 4; i++) {
            buche[i] = new Buca();
            getContentPane().add(buche[i]);
            talpe[i] = new Talpa(buche[i]);
            talpe[i].start();
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new InterfacciaTalpa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
